In [1]:
import pandas as pd

file_path = "../data/raw/Online_Retail.xlsx"
sales = pd.read_excel(file_path)

In [7]:
sales.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
sales.isna().mean() * 100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

In [37]:
quality_missing = pd.DataFrame({
    "missing count": sales.isna().sum(),
    "missing percentage": sales.isna().mean() * 100
})
quality_missing

             missing count  missing percentage
InvoiceNo                0            0.000000
StockCode                0            0.000000
Description           1454            0.268311
Quantity                 0            0.000000
InvoiceDate              0            0.000000
UnitPrice                0            0.000000
CustomerID          135080           24.926694
Country                  0            0.000000

In [38]:
sales.duplicated().sum()

np.int64(5268)

In [39]:
sales.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

In [ ]:
print(sales["Country"].nunique())
print(sales["Country"].value_counts())

38
541909

In [54]:
print(sales["Description"].nunique())
print(sales["Description"].value_counts())

4223
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
                                      ...
LETTER "U" BLING KEY RING                1
wet                                      1
wet boxes                                1
????damages????                          1
lost                                     1
Name: count, Length: 4223, dtype: int64

In [57]:
sales["Quantity"].describe()

count    541909.000000
mean          9.552250
std         218.081158
min      -80995.000000
25%           1.000000
50%           3.000000
75%          10.000000
max       80995.000000
Name: Quantity, dtype: float64

In [59]:
sales["UnitPrice"].describe()

count    541909.000000
mean          4.611114
std          96.759853
min      -11062.060000
25%           1.250000
50%           2.080000
75%           4.130000
max       38970.000000
Name: UnitPrice, dtype: float64

In [82]:
sales[(sales["UnitPrice"] < 0) | (sales["UnitPrice"] == 0)]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

In [64]:
(sales["Quantity"] < 0).sum()

np.int64(10624)

In [ ]:
quality_report = pd.DataFrame({
    "columns": sales.columns,
    "data types": sales.dtypes.astype(str).values,
    "missing count": sales.isna().sum(),
    "missing percentage": (sales.isna().mean() * 100).values,
    "duplicated": sales.duplicated().sum(),
    "unique count": sales.nunique().values
})
quality_report

,columns,data types,missing count,missing percentage,duplicated,unique count
InvoiceNo,InvoiceNo,object,0,0.000000,5268,25900
StockCode,StockCode,object,0,0.000000,5268,4070
Description,Description,object,1454,0.268311,5268,4223
Quantity,Quantity,int64,0,0.000000,5268,722
InvoiceDate,InvoiceDate,datetime64[us],0,0.000000,5268,23260
UnitPrice,UnitPrice,float64,0,0.000000,5268,1630
CustomerID,CustomerID,float64,135080,24.926694,5268,4372
Country,Country,str,0,0.000000,5268,38

: