In [4]:
import pandas as pd

In [ ]:
file_path = "../data/raw/online_Retail.xlsx"
sales = pd.read_excel(file_path)
sales

In [246]:
quality_report = pd.DataFrame({
    "columns": sales.columns,
    "data types": sales.dtypes.astype(str).values,
    "missing count": sales.isna().sum(),
    "missing percentage": (sales.isna().mean() * 100).values,
    "duplicated": sales.duplicated().sum(),
    "unique count": sales.nunique().values
})
quality_report

,columns,data types,missing count,missing percentage,duplicated,unique count
InvoiceNo,InvoiceNo,object,0,0.000000,5268,25900
StockCode,StockCode,object,0,0.000000,5268,4070
Description,Description,object,1454,0.268311,5268,4223
Quantity,Quantity,int64,0,0.000000,5268,722
InvoiceDate,InvoiceDate,datetime64[us],0,0.000000,5268,23260
UnitPrice,UnitPrice,float64,0,0.000000,5268,1630
CustomerID,CustomerID,float64,135080,24.926694,5268,4372
Country,Country,str,0,0.000000,5268,38

In [247]:
sales.shape

(541909, 8)

In [248]:
sales.duplicated().sum()

np.int64(5268)

In [249]:
sales = sales.drop_duplicates()
sales.duplicated().sum()

np.int64(0)

In [250]:
sales.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [251]:
sales["CustomerID"].isna().sum()

np.int64(135037)

In [252]:
sales = sales.dropna(subset = ["CustomerID"])

In [253]:
sales["CustomerID"].isnull().sum()

np.int64(0)

In [254]:
sales["Quantity"].describe()

count    401604.000000
mean         12.183273
std         250.283037
min      -80995.000000
25%           2.000000
50%           5.000000
75%          12.000000
max       80995.000000
Name: Quantity, dtype: float64

In [255]:
(sales["Quantity"] == 0).sum()

np.int64(0)

In [256]:
sales = sales[sales["Quantity"] > 0]

In [257]:

(sales["Quantity"] < 0).sum()

np.int64(0)

In [258]:
sales["UnitPrice"].isna().sum()

np.int64(0)

In [259]:
(sales["UnitPrice"] == 0)

0         False
1         False
2         False
3         False
4         False
          ...
541904    False
541905    False
541906    False
541907    False
541908    False
Name: UnitPrice, Length: 392732, dtype: bool

In [260]:

sales[(sales["UnitPrice"] < 0) | (sales["UnitPrice"] == 0).sum()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [261]:
sales["CustomerID"].dtype

dtype('float64')

In [262]:
sales["CustomerID"] = sales["CustomerID"].astype("int64")

In [263]:
sales["CustomerID"].dtype

dtype('int64')

In [264]:
sales["StockCode"].dtype

dtype('O')

In [266]:
sales["UnitPrice"].dtype

dtype('float64')

In [267]:
sales = sales[sales["UnitPrice"] > 0]

In [274]:
print("missing values:",sales.isna().sum())
print("Duplicated value:", sales.duplicated().sum())
print("negative values in Quantity:",(sales["Quantity"] < 0).sum())
print("negative values in unitPrice:", (sales["UnitPrice"] < 0).sum())
print(sales.dtypes)

missing values: InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64
Duplicated value: 0
negative values in Quantity: 0
negative values in unitPrice: 0
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID              int64
Country                   str
dtype: object

In [275]:
sales

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

In [ ]:
sales.to_excel("../data/interim/cleaned_online_retail.xlsx")

NameError: name 'sales' is not defined

In [5]:
sales = pd.read_excel("../data/interim/cleaned_online_retail.xlsx")

In [7]:
sales["UnitPrice"].describe()

count    392692.000000
mean          3.125914
std          22.241836
min           0.001000
25%           1.250000
50%           1.950000
75%           3.750000
max        8142.750000
Name: UnitPrice, dtype: float64