In [27]:
import pandas as pd
import numpy as np

In [2]:
file_path = "../data/interim/featured_online_retail.xlsx"
sales = pd.read_excel(file_path)

In [4]:
sales.head()

,Unnamed: 0.1,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,...,Hour,Dayofweek,DayName,MonthName,TotalAmount,Isweekend,TimePeriod,CustomerTotalSpend,CustomerPurchaseFrequency,CustomerAvgOrderValue
0,0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,...,8,2,Wednesday,December,15.30,False,morning,5391.21,34,158.565
1,1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,...,8,2,Wednesday,December,20.34,False,morning,5391.21,34,158.565
2,2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,...,8,2,Wednesday,December,22.00,False,morning,5391.21,34,158.565
3,3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,...,8,2,Wednesday,December,20.34,False,morning,5391.21,34,158.565
4,4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,...,8,2,Wednesday,December,20.34,False,morning,5391.21,34,158.565

In [16]:
sales.select_dtypes(include=["object","str"])

,StockCode,Description,DayName,MonthName,TimePeriod
0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,Wednesday,December,morning
1,71053,WHITE METAL LANTERN,Wednesday,December,morning
2,84406B,CREAM CUPID HEARTS COAT HANGER,Wednesday,December,morning
3,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,Wednesday,December,morning
4,84029E,RED WOOLLY HOTTIE WHITE HEART.,Wednesday,December,morning
...,...,...,...,...,...
392687,22613,PACK OF 20 SPACEBOY NAPKINS,Friday,December,afternoon
392688,22899,CHILDREN'S APRON DOLLY GIRL,Friday,December,afternoon
392689,23254,CHILDRENS CUTLERY DOLLY GIRL,Friday,December,afternoon
392690,23255,CHILDRENS CUTLERY CIRCUS PARADE,Friday,December,afternoon
392691,22138,BAKING SET 9 PIECE RETROSPOT,Friday,December,afternoon

In [25]:
sales = pd.get_dummies(
    sales,
    columns= ["Country"],
    dtype= int
)
sales

KeyError: "None of [Index(['Country'], dtype='str')] are in the [columns]"

In [19]:
sales["DayName"]

0         Wednesday
1         Wednesday
2         Wednesday
3         Wednesday
4         Wednesday
            ...
392687       Friday
392688       Friday
392689       Friday
392690       Friday
392691       Friday
Name: DayName, Length: 392692, dtype: str

In [20]:
sales = pd.get_dummies(
    sales,
    columns=["DayName"],
    dtype= int
)
sales

,Unnamed: 0.1,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Year,...,Country_USA,Country_United Arab Emirates,Country_United Kingdom,Country_Unspecified,DayName_Friday,DayName_Monday,DayName_Sunday,DayName_Thursday,DayName_Tuesday,DayName_Wednesday
0,0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,2010,...,0,0,1,0,0,0,0,0,0,1
1,1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,2010,...,0,0,1,0,0,0,0,0,0,1
2,2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,2010,...,0,0,1,0,0,0,0,0,0,1
3,3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,2010,...,0,0,1,0,0,0,0,0,0,1
4,4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,2010,...,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392687,392687,541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,2011,...,0,0,0,0,1,0,0,0,0,0
392688,392688,541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,2011,...,0,0,0,0,1,0,0,0,0,0
392689,392689,541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,2011,...,0,0,0,0,1,0,0,0,0,0
392690,392690,541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,2011,...,0,0,0,0,1,0,0,0,0,0
392691,392691,541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,2011,...,0,0,0,0,1,0,0,0,0,0

In [24]:
sales = sales.drop(columns=["DayName_Friday","DayName_Monday","DayName_Sunday","DayName_Thursday","DayName_Tuesday","DayName_Wednesday"])

In [41]:
sales["Day_sin"] = np.sin(2 * np.pi * sales["Dayofweek"] / 7)
sales["Day_cos"] = np.cos(2 * np.pi * sales["Dayofweek"] / 7)

sales["Month_sin"] = np.sin(2 * np.pi * sales["Month"] / 12)
sales["Month_cos"] = np.cos(2 * np.pi * sales["Month"] / 12)

In [ ]:
sales = sales.drop(columns = ["MonthName"])

,Unnamed: 0.1,Unnamed: 0,InvoiceNo,StockCode,Quantity,InvoiceDate,UnitPrice,CustomerID,Year,Month,...,Country_Sweden,Country_Switzerland,Country_USA,Country_United Arab Emirates,Country_United Kingdom,Country_Unspecified,Day_sin,Day_cos,Month_sin,Month_cos
0,0,0,536365,85123A,6,2010-12-01 08:26:00,2.55,17850,2010,12,...,0,0,0,0,1,0,0.974928,-0.222521,-2.449294e-16,1.0
1,1,1,536365,71053,6,2010-12-01 08:26:00,3.39,17850,2010,12,...,0,0,0,0,1,0,0.974928,-0.222521,-2.449294e-16,1.0
2,2,2,536365,84406B,8,2010-12-01 08:26:00,2.75,17850,2010,12,...,0,0,0,0,1,0,0.974928,-0.222521,-2.449294e-16,1.0
3,3,3,536365,84029G,6,2010-12-01 08:26:00,3.39,17850,2010,12,...,0,0,0,0,1,0,0.974928,-0.222521,-2.449294e-16,1.0
4,4,4,536365,84029E,6,2010-12-01 08:26:00,3.39,17850,2010,12,...,0,0,0,0,1,0,0.974928,-0.222521,-2.449294e-16,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
392687,392687,541904,581587,22613,12,2011-12-09 12:50:00,0.85,12680,2011,12,...,0,0,0,0,0,0,-0.433884,-0.900969,-2.449294e-16,1.0
392688,392688,541905,581587,22899,6,2011-12-09 12:50:00,2.10,12680,2011,12,...,0,0,0,0,0,0,-0.433884,-0.900969,-2.449294e-16,1.0
392689,392689,541906,581587,23254,4,2011-12-09 12:50:00,4.15,12680,2011,12,...,0,0,0,0,0,0,-0.433884,-0.900969,-2.449294e-16,1.0
392690,392690,541907,581587,23255,4,2011-12-09 12:50:00,4.15,12680,2011,12,...,0,0,0,0,0,0,-0.433884,-0.900969,-2.449294e-16,1.0
392691,392691,541908,581587,22138,3,2011-12-09 12:50:00,4.95,12680,2011,12,...,0,0,0,0,0,0,-0.433884,-0.900969,-2.449294e-16,1.0

In [36]:
sales = sales.drop(columns = ["Description"])

In [38]:
sales.dtypes

Unnamed: 0.1                             int64
Unnamed: 0                               int64
InvoiceNo                                int64
StockCode                               object
Quantity                                 int64
InvoiceDate                     datetime64[us]
UnitPrice                              float64
CustomerID                               int64
Year                                     int64
Month                                    int64
Day                                      int64
Hour                                     int64
Dayofweek                                int64
MonthName                                  str
TotalAmount                            float64
Isweekend                                 bool
TimePeriod                                 str
CustomerTotalSpend                     float64
CustomerPurchaseFrequency                int64
CustomerAvgOrderValue                  float64
Country_Australia                        int64
Country_Austria                          int64
Country_Bahrain                          int64
Country_Belgium                          int64
Country_Brazil                           int64
Country_Canada                           int64
Country_Channel Islands                  int64
Country_Cyprus                           int64
Country_Czech Republic                   int64
Country_Denmark                          int64
Country_EIRE                             int64
Country_European Community               int64
Country_Finland                          int64
Country_France                           int64
Country_Germany                          int64
Country_Greece                           int64
Country_Iceland                          int64
Country_Israel                           int64
Country_Italy                            int64
Country_Japan                            int64
Country_Lebanon                          int64
Country_Lithuania                        int64
Country_Malta                            int64
Country_Netherlands                      int64
Country_Norway                           int64
Country_Poland                           int64
Country_Portugal                         int64
Country_RSA                              int64
Country_Saudi Arabia                     int64
Country_Singapore                        int64
Country_Spain                            int64
Country_Sweden                           int64
Country_Switzerland                      int64
Country_USA                              int64
Country_United Arab Emirates             int64
Country_United Kingdom                   int64
Country_Unspecified                      int64
Day_sin                                float64
Day_cos                                float64
dtype: object

In [54]:
sales.to_excel("../data/interim/encoded_online_retail.xlsx")