In [38]:
import pandas as pd

In [51]:
file_path = "../data/interim/encoded_online_retail.xlsx"
sales = pd.read_excel(file_path)

In [52]:
print(sales.shape)
print(sales.head(8))
print(sales.tail())
print(sales.columns.to_list())

(392692, 62)
   Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  InvoiceNo StockCode  Quantity  \
0             0             0           0     536365    85123A         6
1             1             1           1     536365     71053         6
2             2             2           2     536365    84406B         8
3             3             3           3     536365    84029G         6
4             4             4           4     536365    84029E         6
5             5             5           5     536365     22752         2
6             6             6           6     536365     21730         6
7             7             7           7     536366     22633         6

          InvoiceDate  UnitPrice  CustomerID  Year  ...  Country_Sweden  \
0 2010-12-01 08:26:00       2.55       17850  2010  ...               0
1 2010-12-01 08:26:00       3.39       17850  2010  ...               0
2 2010-12-01 08:26:00       2.75       17850  2010  ...               0
3 2010-12-01 08:26:00       3.39       17850  2010  ...               0
4 2010-12-01 08:26:00       3.39       17850  2010  ...               0
5 2010-12-01 08:26:00       7.65       17850  2010  ...               0
6 2010-12-01 08:26:00       4.25       17850  2010  ...               0
7 2010-12-01 08:28:00       1.85       17850  2010  ...               0

   Country_Switzerland  Country_USA  Country_United Arab Emirates  \
0                    0            0                             0
1                    0            0                             0
2                    0            0                             0
3                    0            0                             0
4                    0            0                             0
5                    0            0                             0
6                    0            0                             0
7                    0            0                             0

  Country_United Kingdom  Country_Unspecified   Day_sin   Day_cos  \
0                      1                    0  0.974928 -0.222521
1                      1                    0  0.974928 -0.222521
2                      1                    0  0.974928 -0.222521
3                      1                    0  0.974928 -0.222521
4                      1                    0  0.974928 -0.222521
5                      1                    0  0.974928 -0.222521
6                      1                    0  0.974928 -0.222521
7                      1                    0  0.974928 -0.222521

      Month_sin  Month_cos
0 -2.449294e-16        1.0
1 -2.449294e-16        1.0
2 -2.449294e-16        1.0
3 -2.449294e-16        1.0
4 -2.449294e-16        1.0
5 -2.449294e-16        1.0
6 -2.449294e-16        1.0
7 -2.449294e-16        1.0

[8 rows x 62 columns]
        Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  InvoiceNo StockCode  Quantity  \
392687        392687        392687      541904     581587     22613        12
392688        392688        392688      541905     581587     22899         6
392689        392689        392689      541906     581587     23254         4
392690        392690        392690      541907     581587     23255         4
392691        392691        392691      541908     581587     22138         3

               InvoiceDate  UnitPrice  CustomerID  Year  ...  Country_Sweden  \
392687 2011-12-09 12:50:00       0.85       12680  2011  ...               0
392688 2011-12-09 12:50:00       2.10       12680  2011  ...               0
392689 2011-12-09 12:50:00       4.15       12680  2011  ...               0
392690 2011-12-09 12:50:00       4.15       12680  2011  ...               0
392691 2011-12-09 12:50:00       4.95       12680  2011  ...               0

        Country_Switzerland  Country_USA  Country_United Arab Emirates  \
392687                    0            0                             0
392688                    0            0                             0
392689                    0            0                             0
392690                    0            0                             0
392691                    0            0                             0

       Country_United Kingdom  Country_Unspecified   Day_sin   Day_cos  \
392687                      0                    0 -0.433884 -0.900969
392688                      0                    0 -0.433884 -0.900969
392689                      0                    0 -0.433884 -0.900969
392690                      0                    0 -0.433884 -0.900969
392691                      0                    0 -0.433884 -0.900969

           Month_sin  Month_cos
392687 -2.449294e-16        1.0
392688 -2.449294e-16        1.0
392689 -2.449294e-16        1.0
392690 -2.449294e-16        1.0
392691 -2.449294e-16        1.0

[5 rows x 62 columns]
['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0', 'InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Year', 'Month', 'Day', 'Hour', 'Dayofweek', 'MonthName', 'TotalAmount', 'Isweekend', 'TimePeriod', 'CustomerTotalSpend', 'CustomerPurchaseFrequency', 'CustomerAvgOrderValue', 'Country_Australia', 'Country_Austria', 'Country_Bahrain', 'Country_Belgium', 'Country_Brazil', 'Country_Canada', 'Country_Channel Islands', 'Country_Cyprus', 'Country_Czech Republic', 'Country_Denmark', 'Country_EIRE', 'Country_European Community', 'Country_Finland', 'Country_France', 'Country_Germany', 'Country_Greece', 'Country_Iceland', 'Country_Israel', 'Country_Italy', 'Country_Japan', 'Country_Lebanon', 'Country_Lithuania', 'Country_Malta', 'Country_Netherlands', 'Country_Norway', 'Country_Poland', 'Country_Portugal', 'Country_RSA', 'Country_Saudi Arabia', 'Country_Singapore', 'Country_Spain', 'Country_Sweden', 'Country_Switzerland', 'Country_USA', 'Country_United Arab Emirates', 'Country_United Kingdom', 'Country_Unspecified', 'Day_sin', 'Day_cos', 'Month_sin', 'Month_cos']

In [53]:
sales.isna().sum()

Unnamed: 0.2           0
Unnamed: 0.1           0
Unnamed: 0             0
InvoiceNo              0
StockCode              0
                      ..
Country_Unspecified    0
Day_sin                0
Day_cos                0
Month_sin              0
Month_cos              0
Length: 62, dtype: int64

In [54]:
sales["InvoiceDate"].dtype

dtype('<M8[us]')

In [43]:
sales["InvoiceDate"]

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
392687   2011-12-09 12:50:00
392688   2011-12-09 12:50:00
392689   2011-12-09 12:50:00
392690   2011-12-09 12:50:00
392691   2011-12-09 12:50:00
Name: InvoiceDate, Length: 392692, dtype: datetime64[us]

In [55]:
sales["Date"] = sales["InvoiceDate"].dt.normalize()

In [56]:
sales[["InvoiceDate","Date"]].head()

          InvoiceDate       Date
0 2010-12-01 08:26:00 2010-12-01
1 2010-12-01 08:26:00 2010-12-01
2 2010-12-01 08:26:00 2010-12-01
3 2010-12-01 08:26:00 2010-12-01
4 2010-12-01 08:26:00 2010-12-01

In [77]:
daily_sales = sales.groupby("Date")["TotalAmount"].sum().reset_index()
daily_sales.head()

        Date  TotalAmount
0 2010-12-01     46192.49
1 2010-12-02     47197.57
2 2010-12-03     23876.63
3 2010-12-05     31361.28
4 2010-12-06     31009.33

In [81]:
daily_sales = daily_sales.rename(
    columns={"TotalAmount":"Daily_sales"}
)
daily_sales.head()

        Date  Daily_sales
0 2010-12-01     46192.49
1 2010-12-02     47197.57
2 2010-12-03     23876.63
3 2010-12-05     31361.28
4 2010-12-06     31009.33

In [84]:
sales = sales.drop(columns=["Unnamed: 0.2","Unnamed: 0.1","Unnamed: 0"])

In [95]:
sales["Day"].max()

31

In [ ]:
x = sales[["Quantity","UnitPrice"]]
x.head(10)

In [99]:
y = sales["TotalAmount"]
y.head(10)

0    15.30
1    20.34
2    22.00
3    20.34
4    20.34
5    15.30
6    25.50
7    11.10
8    11.10
9    54.08
Name: TotalAmount, dtype: float64

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
x_train, x_test, y_train, y_test = train_test_split(
    x,y, test_size=0.2, random_state=42
)

In [102]:
print("X_train:", x_train.shape)
print("X_test :", x_test.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (314153, 2)
X_test : (78539, 2)
y_train: (314153,)
y_test : (78539,)

In [103]:
print(x_train.isnull().sum())
print(x_test.isnull().sum())

print(y_train.isnull().sum())
print(y_test.isnull().sum())

Quantity     0
UnitPrice    0
dtype: int64
Quantity     0
UnitPrice    0
dtype: int64
0
0

In [104]:
sales.to_excel(
    "../data/processed/ml_ready_online_retail.xlsx"
)